/**
 * Builds console/app.js — the browser bundle.
 *
 * There is no bundler dependency. The compiled ESM in packages/*|/dist is
 * already browser-compatible except for two things, both handled here:
 *
 *   1. bare specifiers ('@switchboard/catalog') → relative paths
 *   2. node:sqlite, which the browser has no business loading
 *
 * The SQLite adapter is therefore excluded and replaced by SnapshotGraph, which
 * implements the same CatalogGraph interface. Everything downstream of that
 * interface — propagation, rule order, rationale wording, trace construction,
 * intent routing, template filling — is the SAME COMPILED CODE the test suite
 * runs. The console does not reimplement the gate; it calls it.
 *
 * The catalog snapshot is generated from the SQLite fixture at build time, so
 * the browser's data cannot drift from what the suite tests either.
 *
 * Run: npm run build:console   (invoked by npm run bench and by CI)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const require_ = createRequire(import.meta.url);
const { DatabaseSync } = require_('node:sqlite');

// ── 1. snapshot the catalog straight out of the fixture ─────────────────────
const db = new DatabaseSync(':memory:');
db.exec(readFileSync(join(root, 'packages/catalog/schema.sql'), 'utf8'));
db.exec(readFileSync(join(root, 'packages/catalog/fixtures/rosewood.sql'), 'utf8'));
db.exec(readFileSync(join(root, 'packages/catalog/fixtures/rosewood-data.sql'), 'utf8'));

const fields = {};
for (const r of db
  .prepare(
    `SELECT dataset_name || '.' || name AS k, classification, justification
     FROM field ORDER BY k`,
  )
  .all()) {
  fields[r.k] = { classification: r.classification, justification: r.justification };
}

const edges = db
  .prepare(
    `SELECT from_dataset || '.' || from_field AS "from",
            to_dataset   || '.' || to_field   AS "to",
            transform
     FROM lineage_edge ORDER BY "from", "to"`,
  )
  .all();

const values = {};
for (const r of db
  .prepare(
    `SELECT table_name || '.' || field_name AS k, subject_id, value
     FROM row_store ORDER BY k, subject_id`,
  )
  .all()) {
  (values[r.k] ??= {})[r.subject_id] = r.value;
}
db.close();

const snapshot = { fields, edges, values };

// ── 2. concatenate the compiled core + reasoner, stripping module syntax ────
/** Reads a compiled module and removes import/export statements. */
function inline(relPath) {
  const src = readFileSync(join(root, relPath), 'utf8');
  return src
    .split('\n')
    .filter((line) => {
      const t = line.trim();
      if (t.startsWith('import ')) return false; // resolved by concatenation order
      if (t.startsWith('export {') || t.startsWith('export * ')) return false;
      return true;
    })
    .map((line) =>
      // `export class X` / `export function x` / `export const x` → bare decl
      line.replace(/^export (class|function|const|let|var|async function) /, '$1 '),
    )
    .join('\n');
}

// Order matters: core before reasoner, since the reasoner calls into it.
const parts = [
  '// GENERATED by scripts/build-console.mjs — do not edit.',
  '// Concatenated from the SAME compiled output the test suite imports:',
  '//   packages/catalog/dist/core.js      (the gate)',
  '//   packages/reasoner/dist/deterministic.js  (intent routing + templates)',
  '// The catalog snapshot below is generated from packages/catalog/fixtures/,',
  '// so the console cannot drift from the fixture the suite tests.',
  '',
  inline('packages/catalog/dist/core.js'),
  inline('packages/reasoner/dist/deterministic.js'),
  '',
  `export const SNAPSHOT = ${JSON.stringify(snapshot, null, 2)};`,
  '',
  '// The exports the page consumes. Everything above is unmodified compiled code.',
  'export { adjudicate, effectiveOf, evaluate, SnapshotGraph, keyOf, refOf,',
  '         RESTRICTION_ORDER, NEVER_DISCLOSABLE, rank };',
  'export { DeterministicReasoner, INTENT_FIELDS, normalize };',
  '',
];

mkdirSync(join(root, 'console'), { recursive: true });
writeFileSync(join(root, 'console/app.js'), parts.join('\n'));

console.log(
  `wrote console/app.js — ${Object.keys(fields).length} fields, ` +
    `${edges.length} lineage edges, ${Object.keys(values).length} valued fields`,
);
