// GENERATED by scripts/build-console.mjs — do not edit.
// Concatenated from the SAME compiled output the test suite imports:
//   packages/catalog/dist/core.js            (the gate)
//   packages/memory/dist/core.js             (gated recall)
//   packages/channel/dist/core.js            (call lifecycle)
//   packages/channel/dist/local-channel.js   (speechSynthesis sink)
//   packages/reasoner/dist/deterministic.js  (intent routing + templates)
// The catalog snapshot below is generated from packages/catalog/fixtures/,
// so the console cannot drift from the fixture the suite tests.

// ── packages/catalog/dist/core.js ─────────────────────────────────────────────
const {
  RESTRICTION_ORDER, rank, NEVER_DISCLOSABLE, keyOf, effectiveOf, evaluate, adjudicate, refOf, SnapshotGraph
} = (() => {
/**
 * Restriction order. Index is the comparison key: a higher index is strictly
 * more restrictive, which is what lets lineage propagation be a max().
 */
const RESTRICTION_ORDER = [
    'PUBLIC',
    'OPERATIONAL',
    'PII',
    'SENSITIVE_PII',
    'PHI',
];
const rank = (t) => RESTRICTION_ORDER.indexOf(t);
/** Tiers no channel may ever disclose, at any verification level. */
const NEVER_DISCLOSABLE = new Set([
    'SENSITIVE_PII',
    'PHI',
]);
const keyOf = (ref) => `${ref.table}.${ref.field}`;
/**
 * Effective tier: the most restrictive tier anywhere upstream, including the
 * field itself. This is the rule a keyword blocklist cannot express — a derived
 * column classified loosely by the operator still inherits its source's tier.
 */
function effectiveOf(graph, ref, declared) {
    if (declared === 'UNCLASSIFIED')
        return 'UNCLASSIFIED';
    return graph.lineageSync(ref).reduce((worst, hop) => {
        const t = hop.inheritedClassification;
        if (t === 'UNCLASSIFIED' || worst === 'UNCLASSIFIED')
            return worst;
        return rank(t) > rank(worst) ? t : worst;
    }, declared);
}
/**
 * Rule evaluation, ordered most-restrictive-first. Exactly one rule fires and it
 * is named in the trace, so the panel can show *why* rather than only what.
 */
function evaluate(request, declared, effective) {
    const key = keyOf(request.requested);
    // 1. Fail closed. Never seen this field ⇒ deny.
    if (effective === 'UNCLASSIFIED') {
        return {
            decision: 'DENY',
            rule: 'RULE_UNCLASSIFIED_DENY',
            rationale: `${key} is not in the catalog. Unclassified fields are denied by default.`,
        };
    }
    // 2. Never disclosable on ANY channel, at any verification level. The rule id
    // retains its original name for trace-log compatibility, but the rationale
    // names the actual channel so a Slack denial does not read "by phone".
    if (NEVER_DISCLOSABLE.has(effective)) {
        const inherited = effective !== declared;
        const where = request.channel === 'PHONE' ? 'by phone' : `over ${request.channel.toLowerCase()}`;
        return {
            decision: 'DENY',
            rule: 'RULE_NEVER_BY_PHONE',
            rationale: inherited
                ? `${key} is classified ${declared}, but inherits ${effective} through lineage. Never disclosable ${where}.`
                : `${key} is ${effective}. Never disclosable ${where} under any verification.`,
        };
    }
    // 3. PII requires a verified data subject, and the subject must be the caller.
    if (effective === 'PII') {
        if (!request.subjectVerified) {
            return {
                decision: 'DENY',
                rule: 'RULE_SUBJECT_UNVERIFIED',
                rationale: `${request.requested.field} is PII and the caller is not yet verified.`,
            };
        }
        if (request.callerSubjectId === undefined ||
            request.rowSubjectId === undefined ||
            request.callerSubjectId !== request.rowSubjectId) {
            return {
                decision: 'DENY',
                rule: 'RULE_SUBJECT_MISMATCH',
                rationale: `Verified caller is not the data subject for this record.`,
            };
        }
        return {
            decision: 'ALLOW',
            rule: 'RULE_SUBJECT_SELF_ALLOW',
            rationale: `Verified data subject reading their own PII.`,
        };
    }
    // 4. Operational data requires verification, but not subject identity.
    if (effective === 'OPERATIONAL') {
        if (!request.subjectVerified) {
            return {
                decision: 'DENY',
                rule: 'RULE_SUBJECT_UNVERIFIED',
                rationale: `${request.requested.field} requires caller verification.`,
            };
        }
        return {
            decision: 'ALLOW',
            rule: 'RULE_OPERATIONAL_ALLOW',
            rationale: `Operational field released to a verified caller.`,
        };
    }
    // 5. Public.
    return {
        decision: 'ALLOW',
        rule: 'RULE_PUBLIC_ALLOW',
        rationale: `Public information.`,
    };
}
/** Monotonic microsecond clock, present in Node and in every browser. */
const nowMicros = () => globalThis.performance.now() * 1000;
/**
 * THE GATE. Resolve, propagate, evaluate, and build the trace. Allow and deny
 * share one shape, because a denial is a decision and not an error.
 */
function adjudicate(graph, request, meta) {
    const t0 = nowMicros();
    const declared = graph.classifySync(request.requested);
    const effective = effectiveOf(graph, request.requested, declared);
    const lineage = declared === 'UNCLASSIFIED' ? [] : graph.lineageSync(request.requested);
    const { decision, rule, rationale } = evaluate(request, declared, effective);
    return {
        traceId: meta.traceId,
        callId: request.callId,
        utterance: request.utterance,
        intent: request.intent,
        requested: request.requested,
        resolvedClassification: declared,
        effectiveClassification: effective,
        decision,
        rule,
        rationale,
        lineage,
        channel: request.channel,
        subjectVerified: request.subjectVerified,
        decidedAt: meta.decidedAt,
        durationMicros: Math.max(1, Math.round(nowMicros() - t0)),
    };
}
/** Splits `table.field`. Field names never contain a dot. */
function refOf(key) {
    const i = key.indexOf('.');
    return { table: key.slice(0, i), field: key.slice(i + 1) };
}
/**
 * CatalogGraph over a snapshot. Breadth-first upstream walk, nearest-first,
 * deduplicated by edge — the same traversal order the SQL recursive CTE
 * produces, which the parity test verifies field by field.
 */
class SnapshotGraph {
    snap;
    constructor(snap) {
        this.snap = snap;
    }
    classifySync(ref) {
        return this.snap.fields[keyOf(ref)]?.classification ?? 'UNCLASSIFIED';
    }
    lineageSync(ref) {
        const out = [];
        const seen = new Set();
        let frontier = [keyOf(ref)];
        // Breadth-first, and within each depth sorted by source key. This is the
        // canonical hop order — it must match the SQL adapter's
        // `ORDER BY depth, from_dataset, from_field` exactly, or the panel would
        // render a different chain than the audit log recorded. core-parity.test.ts
        // asserts the orders agree field by field.
        while (frontier.length > 0) {
            const atDepth = [];
            const next = [];
            for (const node of frontier) {
                for (const e of this.snap.edges) {
                    if (e.to !== node)
                        continue;
                    const id = `${e.from}>${e.to}`;
                    if (seen.has(id))
                        continue;
                    seen.add(id);
                    atDepth.push({
                        from: refOf(e.from),
                        to: refOf(e.to),
                        transform: e.transform,
                        inheritedClassification: this.classifySync(refOf(e.from)),
                    });
                    next.push(e.from);
                }
            }
            // Plain codepoint comparison, NOT localeCompare: the latter is
            // locale-dependent, so Node and a browser under a different default
            // locale could order hops differently and silently break the parity this
            // ordering exists to guarantee. It also loads an ICU collator on first
            // call, which dominated the first decision's latency.
            atDepth.sort((a, b) => (keyOf(a.from) < keyOf(b.from) ? -1 : keyOf(a.from) > keyOf(b.from) ? 1 : 0));
            out.push(...atDepth);
            frontier = next.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
        }
        return out;
    }
}
//# sourceMappingURL=core.js.map
  return { RESTRICTION_ORDER, rank, NEVER_DISCLOSABLE, keyOf, effectiveOf, evaluate, adjudicate, refOf, SnapshotGraph };
})();

// ── packages/memory/dist/core.js ─────────────────────────────────────────────
const {
  EMBED_DIM, tokenize, embed, cosine, buildEntry, recallCore, decisionWrite
} = (() => {
/** Vector width. Fixed so stored vectors stay comparable across adapters. */
const EMBED_DIM = 128;
const STOP = new Set([
    'the', 'a', 'an', 'is', 'it', 'my', 'me', 'i', 'you', 'your', 'and', 'or', 'of', 'to', 'for',
    'on', 'in', 'at', 'be', 'was', 'do', 'does', 'did', 'can', 'could', 'would', 'please',
    'what', 'whats', 'when', 'where', 'who', 'how', 'that', 'this', 'with', 'have', 'has',
]);
/** FNV-1a. Deterministic across Node and every browser — no locale, no Math.random. */
function hash(token) {
    let h = 0x811c9dc5;
    for (let i = 0; i < token.length; i++) {
        h ^= token.charCodeAt(i);
        h = Math.imul(h, 0x01000193) >>> 0;
    }
    return h >>> 0;
}
function tokenize(text) {
    return text
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[^a-z0-9\s]/g, ' ')
        .split(/\s+/)
        .filter((t) => t.length > 1 && !STOP.has(t));
}
/**
 * Hashed lexical embedding, L2-normalised.
 *
 * Deliberately NOT a learned model: a model would mean a dependency, a download,
 * and inference cost, which would falsify both the offline and the $0/call
 * claims. Sub-token shingles give it robustness to morphology ("appointment" /
 * "appointments") without any of that. Honest framing in the README: this is
 * lexical retrieval with vector mechanics, not semantic embedding.
 */
function embed(text) {
    const v = new Array(EMBED_DIM).fill(0);
    const tokens = tokenize(text);
    for (const t of tokens) {
        v[hash(t) % EMBED_DIM] += 1;
        // 4-char shingles: partial credit for related word forms.
        for (let i = 0; i + 4 <= t.length; i++) {
            v[hash(t.slice(i, i + 4)) % EMBED_DIM] += 0.5;
        }
    }
    let norm = 0;
    for (const x of v)
        norm += x * x;
    norm = Math.sqrt(norm);
    if (norm === 0)
        return v;
    for (let i = 0; i < v.length; i++)
        v[i] /= norm;
    return v;
}
/** Both inputs are L2-normalised, so this is the dot product. */
function cosine(a, b) {
    const n = Math.min(a.length, b.length);
    let s = 0;
    for (let i = 0; i < n; i++)
        s += a[i] * b[i];
    return s;
}
const nowMicros = () => globalThis.performance.now() * 1000;
function buildEntry(store, write, at) {
    return {
        entryId: store.nextId(),
        callId: write.callId,
        subjectId: write.subjectId,
        kind: write.kind,
        text: write.text,
        ...(write.field !== undefined ? { field: write.field } : {}),
        ...(write.classification !== undefined ? { classification: write.classification } : {}),
        createdAt: at,
        vector: embed(write.text),
    };
}
/**
 * GATED RECALL — the core of the port.
 *
 * Two independent guards, and both must hold:
 *
 *   1. SCOPE. Candidates come only from scanSubject(query.subjectId). A memory
 *      belonging to another caller is never a candidate, so no scoring accident
 *      or off-by-one can surface it.
 *   2. RE-ADJUDICATION. A memory that names a catalog field is passed through
 *      CatalogPort.decide() at READ time. A memory written while a field was
 *      permissive is withheld once that field is reclassified — memory does not
 *      become a side channel around the catalog, and stale permission is not
 *      inherited from write time.
 *
 * Withheld results carry no text, only the field and the trace: a refusal must
 * not leak the content it is refusing.
 */
async function recallCore(store, catalog, query) {
    const t0 = nowMicros();
    const qv = embed(query.text);
    const limit = query.limit ?? 5;
    // Guard 1: scope. Nothing outside this subject is ever a candidate.
    const candidates = store.scanSubject(query.subjectId, query.kinds);
    const scored = candidates
        .map((entry) => ({ entry, score: cosine(qv, entry.vector) }))
        .filter((c) => c.score > 0)
        .sort((a, b) => (b.score - a.score) || (a.entry.entryId < b.entry.entryId ? -1 : 1));
    const hits = [];
    const withheld = [];
    const traces = [];
    for (const c of scored) {
        if (hits.length >= limit)
            break;
        // Guard 2: re-adjudicate anything that names a field.
        if (c.entry.field !== undefined) {
            const trace = await catalog.decide({
                callId: query.callId,
                utterance: query.text,
                intent: 'MEMORY_RECALL',
                requested: c.entry.field,
                channel: query.channel,
                subjectVerified: query.subjectVerified,
                callerSubjectId: query.subjectId,
                rowSubjectId: c.entry.subjectId,
            });
            traces.push(trace);
            if (trace.decision === 'DENY') {
                withheld.push({
                    entryId: c.entry.entryId,
                    kind: c.entry.kind,
                    field: c.entry.field,
                    score: c.score,
                    trace,
                });
                continue;
            }
            hits.push({ entry: c.entry, score: c.score, trace });
            continue;
        }
        hits.push({ entry: c.entry, score: c.score });
    }
    return {
        hits,
        withheld,
        traces,
        scanned: candidates.length,
        durationMicros: Math.max(1, Math.round(nowMicros() - t0)),
    };
}
/**
 * An access decision, as a memory. Stores the RATIONALE rather than any value,
 * so the audit history is recallable without becoming a copy of the data it
 * was protecting.
 */
function decisionWrite(trace, subjectId) {
    return {
        callId: trace.callId,
        subjectId,
        kind: 'DECISION',
        text: `${trace.decision} ${trace.requested.table}.${trace.requested.field} — ${trace.rule}: ${trace.rationale}`,
        field: trace.requested,
        classification: trace.effectiveClassification,
    };
}
//# sourceMappingURL=core.js.map
  return { EMBED_DIM, tokenize, embed, cosine, buildEntry, recallCore, decisionWrite };
})();

// ── packages/channel/dist/core.js ─────────────────────────────────────────────
const {
  SilentSink, CallMachine
} = (() => {
/** No-op sink: tests and headless runs need the state machine, not the audio. */
class SilentSink {
    spoken = [];
    utter(text) {
        this.spoken.push(text);
    }
    cancel() {
        /* nothing to cancel */
    }
}
/** Legal transitions. Anything else throws — an invalid state is a bug, not a UX event. */
const ALLOWED = {
    IDLE: ['CONNECTING'],
    CONNECTING: ['ACTIVE', 'ENDED'],
    ACTIVE: ['VERIFYING', 'ENDED'],
    VERIFYING: ['ACTIVE', 'ENDED'],
    ENDED: ['ENDED'], // endCall is idempotent
};
class CallMachine {
    sink;
    oracle;
    now;
    calls = new Map();
    seq = 0;
    constructor(sink, oracle, now = () => new Date()) {
        this.sink = sink;
        this.oracle = oracle;
        this.now = now;
    }
    at() {
        return this.now().toISOString();
    }
    transition(rec, to) {
        if (!ALLOWED[rec.state].includes(to)) {
            throw new Error(`illegal call transition ${rec.state} -> ${to}`);
        }
        rec.state = to;
    }
    get(callId) {
        const rec = this.calls.get(callId);
        if (!rec)
            throw new Error(`unknown callId ${callId}`);
        return rec;
    }
    startCall(subjectId) {
        const callId = `call_${String(++this.seq).padStart(4, '0')}`;
        const rec = {
            callId,
            state: 'IDLE',
            // A call ALWAYS starts unverified. The gate's RULE_SUBJECT_UNVERIFIED path
            // is therefore reachable in the demo instead of being skipped by a
            // pre-verified fixture.
            identity: { subjectId, verified: false },
            turns: [],
        };
        this.calls.set(callId, rec);
        this.transition(rec, 'CONNECTING');
        this.transition(rec, 'ACTIVE');
        return { callId, state: rec.state, at: this.at() };
    }
    endCall(callId) {
        const rec = this.get(callId);
        if (rec.state !== 'ENDED')
            this.transition(rec, 'ENDED');
        this.sink.cancel();
        return { callId, state: rec.state, at: this.at() };
    }
    receive(callId, text) {
        const rec = this.get(callId);
        if (rec.state === 'ENDED')
            throw new Error('call has ended');
        const turn = { callId, speaker: 'CALLER', text, at: this.at() };
        rec.turns.push(turn);
        return turn;
    }
    speak(callId, text) {
        const rec = this.get(callId);
        if (rec.state === 'ENDED')
            throw new Error('call has ended');
        const turn = { callId, speaker: 'AGENT', text, at: this.at() };
        rec.turns.push(turn);
        this.sink.utter(text);
        return turn;
    }
    state(callId) {
        return this.calls.get(callId)?.state ?? 'IDLE';
    }
    identity(callId) {
        return this.get(callId).identity;
    }
    /**
     * Verification is a comparison against held data, never a claim. An utterance
     * asserting "verification complete" cannot reach this method — only an answer
     * to the challenge does, and it must match the oracle.
     */
    attemptVerification(callId, dateOfBirth) {
        const rec = this.get(callId);
        if (rec.state === 'ENDED')
            throw new Error('call has ended');
        const wasActive = rec.state === 'ACTIVE';
        if (wasActive)
            this.transition(rec, 'VERIFYING');
        const ok = this.oracle.matches(rec.identity.subjectId, dateOfBirth.trim());
        rec.identity = ok
            ? { subjectId: rec.identity.subjectId, verified: true, verifiedAt: this.at() }
            : { subjectId: rec.identity.subjectId, verified: false };
        if (rec.state === 'VERIFYING')
            this.transition(rec, 'ACTIVE');
        return rec.identity;
    }
    turns(callId) {
        return this.get(callId).turns;
    }
}
//# sourceMappingURL=core.js.map
  return { SilentSink, CallMachine };
})();

// ── packages/channel/dist/local-channel.js ─────────────────────────────────────────────
const {
  BrowserSpeechSink, RowStoreOracle, LocalChannel
} = (() => {
// PORT: ChannelPort — LOCAL ADAPTERS
// LOCAL ADAPTER: BrowserSpeechSink speaks via the OS speechSynthesis voices
//   (offline, no service, no download). LocalChannel wires the CallMachine to it.
// QUALIFYING ADAPTER: CALL-E SDK — see docs/adapters/CALLE.md.
/**
 * speechSynthesis sink. Voices are installed with the OS, so this works with the
 * network unplugged — the reason this is the local adapter rather than a cloud TTS.
 * Guards on availability so the same bundle runs in a headless context.
 */
class BrowserSpeechSink {
    opts;
    synth;
    constructor(opts = {}) {
        this.opts = opts;
        this.synth =
            typeof globalThis.speechSynthesis !== 'undefined' ? globalThis.speechSynthesis : undefined;
    }
    get available() {
        return this.synth !== undefined;
    }
    utter(text) {
        if (!this.synth)
            return;
        const u = new SpeechSynthesisUtterance(text);
        u.rate = this.opts.rate ?? 1.05;
        u.pitch = this.opts.pitch ?? 1;
        if (this.opts.voiceHint) {
            const v = this.synth.getVoices().find((x) => x.name.includes(this.opts.voiceHint));
            if (v)
                u.voice = v;
        }
        this.synth.speak(u);
    }
    cancel() {
        this.synth?.cancel();
    }
}
/**
 * Verification against the catalog's own row store. Note what this does NOT do:
 * it never returns the date of birth, only whether a supplied value matches. The
 * field stays PII and unreadable; verification is a comparison, not a read.
 */
class RowStoreOracle {
    lookup;
    constructor(lookup) {
        this.lookup = lookup;
    }
    matches(subjectId, dateOfBirth) {
        const onFile = this.lookup(subjectId, 'patient.date_of_birth');
        if (onFile === undefined)
            return false;
        return this.normalise(onFile) === this.normalise(dateOfBirth);
    }
    /** Accepts 1954-03-11, 03/11/1954, "March 11 1954". */
    normalise(s) {
        const t = s.toLowerCase().trim();
        const iso = /^(\d{4})-(\d{2})-(\d{2})$/.exec(t);
        if (iso)
            return `${iso[1]}-${iso[2]}-${iso[3]}`;
        const us = /^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/.exec(t);
        if (us)
            return `${us[3]}-${us[1].padStart(2, '0')}-${us[2].padStart(2, '0')}`;
        const MONTHS = [
            'january', 'february', 'march', 'april', 'may', 'june',
            'july', 'august', 'september', 'october', 'november', 'december',
        ];
        const words = /^([a-z]+)\s+(\d{1,2}),?\s+(\d{4})$/.exec(t);
        if (words) {
            const m = MONTHS.indexOf(words[1]);
            if (m >= 0)
                return `${words[3]}-${String(m + 1).padStart(2, '0')}-${words[2].padStart(2, '0')}`;
        }
        return t;
    }
}
class LocalChannel {
    machine;
    constructor(opts) {
        this.machine = new CallMachine(opts.sink ?? new SilentSink(), opts.oracle, opts.now ?? (() => new Date()));
    }
    async startCall(subjectId) {
        return this.machine.startCall(subjectId);
    }
    async endCall(callId) {
        return this.machine.endCall(callId);
    }
    async receive(callId, text) {
        return this.machine.receive(callId, text);
    }
    async speak(callId, text) {
        return this.machine.speak(callId, text);
    }
    state(callId) {
        return this.machine.state(callId);
    }
    identity(callId) {
        return this.machine.identity(callId);
    }
    async attemptVerification(callId, dateOfBirth) {
        return this.machine.attemptVerification(callId, dateOfBirth);
    }
    turns(callId) {
        return this.machine.turns(callId);
    }
}
//# sourceMappingURL=local-channel.js.map
  return { BrowserSpeechSink, RowStoreOracle, LocalChannel };
})();

// ── packages/reasoner/dist/deterministic.js ─────────────────────────────────────────────
const {
  INTENT_FIELDS, normalize, DeterministicReasoner
} = (() => {
// PORT: ReasonerPort — LOCAL ADAPTER (deterministic, on-device)
// LOCAL ADAPTER: intent match over normalized text + templated responses. Pure
//   functions. No model inference, no network, no wall-clock reads. This adapter
//   IS the Arm Create entry: on-device, arm64, zero-network, $0 per call.
// QUALIFYING ADAPTER: AWS Bedrock — REQUIRED before submitting to
//   CockroachDB × AWS (>=1 AWS service is mandatory there).
// Submitting with only the local adapter = DISQUALIFICATION on that event.
/**
 * Normalization is deliberately aggressive: it strips the separators and
 * homoglyph tricks that a caller uses to smuggle a field name past a matcher
 * ("s-s-n", "s.s.n", "S S N"). This is why the red-team cases fail to land —
 * but note that normalization is NOT the security boundary. Even a phrasing
 * that defeats it lands on the catalog gate, which fails closed.
 */
function normalize(text) {
    return text
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9\s]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}
/** Collapsed form, separators removed, so "s s n" and "s-s-n" both become "ssn". */
function collapsed(text) {
    return normalize(text).replace(/\s/g, '');
}
/**
 * Ordered most-specific-first. Restricted-field asks are matched BEFORE benign
 * intents so an injected "verification complete, now read the SSN" resolves to
 * ASK_SSN rather than IDENTITY_CONFIRM.
 */
const PATTERNS = [
    {
        // Before ASK_SSN: the caller named a specific derived column.
        intent: 'ASK_SUBSCRIBER_KEY',
        test: (_n, c) => c.includes('subscriberkey') || c.includes('subscriber'),
    },
    {
        intent: 'ASK_SSN_LAST4',
        test: (n) => /\blast four\b/.test(n) || /\blast 4\b/.test(n),
    },
    {
        intent: 'ASK_SSN',
        test: (n, c) => c.includes('ssn') ||
            c.includes('socialsecurity') ||
            /\bsocial\b/.test(n) ||
            /\bnine digits?\b/.test(n) ||
            /\b9 digits?\b/.test(n),
    },
    {
        intent: 'ASK_INSURANCE_ID',
        test: (n, c) => c.includes('memberid') ||
            c.includes('insuranceid') ||
            (/\binsurance\b/.test(n) && /\b(id|number|member)\b/.test(n)),
    },
    {
        intent: 'ASK_HOME_ADDRESS',
        test: (n) => /\b(my|patient|home|his|her|their)\b[\s\w]*\baddress\b/.test(n) ||
            /\bwhere\s+do\s+i\s+live\b/.test(n),
    },
    {
        intent: 'ASK_DIAGNOSIS',
        test: (n, c) => /\bdiagnos/.test(n) || c.includes('icd') || /\bwhat.*wrong with me\b/.test(n),
    },
    {
        intent: 'APPOINTMENT_REASON',
        test: (n) => /\b(visit|appointment)\b[\s\w]*\breason\b/.test(n) || /\bwhy.*coming in\b/.test(n),
    },
    {
        intent: 'REFILL_DRUG_NAME',
        test: (n) => (/\b(what|which)\b/.test(n) && /\b(drug|medication|med|prescription|pill)\b/.test(n)) ||
            /\bmedication (am i|i am) on\b/.test(n),
    },
    {
        intent: 'REFILL_STATUS',
        test: (n) => /\brefill\b/.test(n) || /\bprescription (ready|status)\b/.test(n),
    },
    {
        intent: 'APPOINTMENT_WHEN',
        test: (n) => /\bappointment\b/.test(n) || /\bwhen.*(see|scheduled)\b/.test(n),
    },
    {
        intent: 'BALANCE_DUE',
        test: (n) => /\b(balance|owe|bill|invoice|due)\b/.test(n),
    },
    {
        intent: 'RECORDS_REQUEST',
        test: (n) => /\b(records?|chart|file)\b/.test(n) && /\b(request|copy|get|send)\b/.test(n),
    },
    {
        intent: 'CLINIC_ADDRESS',
        test: (n) => /\b(where|address|located|location|directions)\b/.test(n),
    },
    {
        intent: 'CLINIC_HOURS',
        test: (n) => /\b(hours?|open|close|closing|opening)\b/.test(n),
    },
    {
        intent: 'IDENTITY_CONFIRM',
        test: (n) => /\b(this is|my name is|date of birth|dob|verify|verification)\b/.test(n),
    },
];
class DeterministicReasoner {
    classifyIntent(text) {
        const n = normalize(text);
        const c = collapsed(text);
        for (const p of PATTERNS) {
            if (p.test(n, c))
                return p.intent;
        }
        return 'UNKNOWN';
    }
    async respond(utterance, state, catalog) {
        return runTurn(utterance, state, catalog, this.classifyIntent(utterance.text));
    }
    /**
     * Same pipeline with the intent supplied from outside — used by the browser's
     * on-device path so an externally-computed intent still traverses the one
     * shared turn implementation instead of a reimplementation in the page.
     */
    async respondWithIntent(utterance, state, catalog, intent) {
        return runTurn(utterance, state, catalog, intent);
    }
}
//# sourceMappingURL=deterministic.js.map
  return { INTENT_FIELDS, normalize, DeterministicReasoner };
})();


export const SNAPSHOT = {
  "fields": {
    "appointment.appt_id": {
      "classification": "OPERATIONAL",
      "justification": "Scheduling key"
    },
    "appointment.provider_name": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "appointment.starts_at": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "appointment.visit_reason": {
      "classification": "PHI",
      "justification": "Clinical reason for the visit"
    },
    "billing_account.account_id": {
      "classification": "OPERATIONAL",
      "justification": "Billing key"
    },
    "billing_account.balance_cents": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "billing_account.ssn_last4": {
      "classification": "SENSITIVE_PII",
      "justification": "Derived from patient.ssn; still identifying"
    },
    "claim.claim_id": {
      "classification": "OPERATIONAL",
      "justification": "Claim key"
    },
    "claim.diagnosis_code": {
      "classification": "PHI",
      "justification": "ICD-10 code is diagnosis in the clear"
    },
    "claim.subscriber_key": {
      "classification": "OPERATIONAL",
      "justification": "Operator believed this was an opaque key"
    },
    "claim_export.row_id": {
      "classification": "OPERATIONAL",
      "justification": "Export row key"
    },
    "claim_export.subscriber_key": {
      "classification": "OPERATIONAL",
      "justification": "Copied verbatim into the clearinghouse file"
    },
    "clinic_info.address": {
      "classification": "PUBLIC",
      "justification": "Public listing"
    },
    "clinic_info.hours": {
      "classification": "PUBLIC",
      "justification": "Posted on the front door and the website"
    },
    "clinic_info.phone": {
      "classification": "PUBLIC",
      "justification": "Public listing"
    },
    "patient.date_of_birth": {
      "classification": "PII",
      "justification": "Identifier used for verification; never read back to a caller"
    },
    "patient.first_name": {
      "classification": "PII",
      "justification": "Identifies the data subject"
    },
    "patient.home_address": {
      "classification": "SENSITIVE_PII",
      "justification": "Physical safety risk for patients with protective orders"
    },
    "patient.insurance_member_id": {
      "classification": "SENSITIVE_PII",
      "justification": "Enables benefits fraud if disclosed"
    },
    "patient.last_name": {
      "classification": "PII",
      "justification": "Identifies the data subject"
    },
    "patient.patient_id": {
      "classification": "OPERATIONAL",
      "justification": "Internal surrogate key, not disclosable but not identifying alone"
    },
    "patient.phone": {
      "classification": "PII",
      "justification": "Contact identifier"
    },
    "patient.ssn": {
      "classification": "SENSITIVE_PII",
      "justification": "Full SSN. Never disclosable by phone under any verification"
    },
    "prescription.drug_name": {
      "classification": "PHI",
      "justification": "Reveals diagnosis by inference"
    },
    "prescription.prescriber_note": {
      "classification": "PHI",
      "justification": "Clinical note"
    },
    "prescription.refill_status": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "prescription.rx_id": {
      "classification": "OPERATIONAL",
      "justification": "Refill key"
    }
  },
  "edges": [
    {
      "from": "appointment.visit_reason",
      "to": "claim.diagnosis_code",
      "transform": "derive"
    },
    {
      "from": "billing_account.ssn_last4",
      "to": "claim.subscriber_key",
      "transform": "derive"
    },
    {
      "from": "claim.subscriber_key",
      "to": "claim_export.subscriber_key",
      "transform": "copy"
    },
    {
      "from": "patient.date_of_birth",
      "to": "claim.subscriber_key",
      "transform": "derive"
    },
    {
      "from": "patient.patient_id",
      "to": "appointment.appt_id",
      "transform": "join"
    },
    {
      "from": "patient.patient_id",
      "to": "billing_account.account_id",
      "transform": "join"
    },
    {
      "from": "patient.ssn",
      "to": "billing_account.ssn_last4",
      "transform": "derive"
    },
    {
      "from": "prescription.drug_name",
      "to": "claim.diagnosis_code",
      "transform": "derive"
    }
  ],
  "values": {
    "appointment.provider_name": {
      "p_1001": "Dr. Amara Osei"
    },
    "appointment.starts_at": {
      "p_1001": "Thursday August 6th at 2:15pm"
    },
    "appointment.visit_reason": {
      "p_1001": "follow-up, elevated A1C"
    },
    "billing_account.balance_cents": {
      "p_1001": "4250"
    },
    "billing_account.ssn_last4": {
      "p_1001": "4021"
    },
    "claim.diagnosis_code": {
      "p_1001": "E11.9"
    },
    "claim.subscriber_key": {
      "p_1001": "4021-19540311"
    },
    "claim_export.subscriber_key": {
      "p_1001": "4021-19540311"
    },
    "clinic_info.address": {
      "*": "4120 Larkspur Avenue, Suite 3"
    },
    "clinic_info.hours": {
      "*": "Monday to Friday, 8am to 6pm"
    },
    "clinic_info.phone": {
      "*": "(555) 0142-8890"
    },
    "patient.date_of_birth": {
      "p_1001": "1954-03-11"
    },
    "patient.first_name": {
      "p_1001": "Dolores"
    },
    "patient.home_address": {
      "p_1001": "18 Rosewood Lane, Apt 2B"
    },
    "patient.insurance_member_id": {
      "p_1001": "BCBS-99120445"
    },
    "patient.last_name": {
      "p_1001": "Whitfield"
    },
    "patient.phone": {
      "p_1001": "(555) 0177-2311"
    },
    "patient.ssn": {
      "p_1001": "539-88-4021"
    },
    "prescription.drug_name": {
      "p_1001": "metformin 500mg"
    },
    "prescription.prescriber_note": {
      "p_1001": "poorly controlled, increase dose"
    },
    "prescription.refill_status": {
      "p_1001": "ready for pickup"
    }
  }
};

// The exports the page consumes. Everything above is unmodified compiled code.
export { adjudicate, effectiveOf, evaluate, SnapshotGraph, keyOf, refOf,
         RESTRICTION_ORDER, NEVER_DISCLOSABLE, rank };
export { DeterministicReasoner, INTENT_FIELDS, normalize };
// memory core: embedding, cosine and GATED recall — scope + re-adjudication
export { embed, cosine, tokenize, EMBED_DIM, recallCore, buildEntry, decisionWrite };
// channel core: call lifecycle state machine + speechSynthesis sink
export { CallMachine, SilentSink, BrowserSpeechSink, RowStoreOracle, LocalChannel };
