// GENERATED by scripts/build-console.mjs — do not edit.
// Concatenated from the SAME compiled output the test suite imports:
//   packages/catalog/dist/core.js      (the gate)
//   packages/reasoner/dist/deterministic.js  (intent routing + templates)
// The catalog snapshot below is generated from packages/catalog/fixtures/,
// so the console cannot drift from the fixture the suite tests.

/**
 * Restriction order. Index is the comparison key: a higher index is strictly
 * more restrictive, which is what lets lineage propagation be a max().
 */
const RESTRICTION_ORDER = [
    'PUBLIC',
    'OPERATIONAL',
    'PII',
    'SENSITIVE_PII',
    'PHI',
];
const rank = (t) => RESTRICTION_ORDER.indexOf(t);
/** Tiers no channel may ever disclose, at any verification level. */
const NEVER_DISCLOSABLE = new Set([
    'SENSITIVE_PII',
    'PHI',
]);
const keyOf = (ref) => `${ref.table}.${ref.field}`;
/**
 * Effective tier: the most restrictive tier anywhere upstream, including the
 * field itself. This is the rule a keyword blocklist cannot express — a derived
 * column classified loosely by the operator still inherits its source's tier.
 */
function effectiveOf(graph, ref, declared) {
    if (declared === 'UNCLASSIFIED')
        return 'UNCLASSIFIED';
    return graph.lineageSync(ref).reduce((worst, hop) => {
        const t = hop.inheritedClassification;
        if (t === 'UNCLASSIFIED' || worst === 'UNCLASSIFIED')
            return worst;
        return rank(t) > rank(worst) ? t : worst;
    }, declared);
}
/**
 * Rule evaluation, ordered most-restrictive-first. Exactly one rule fires and it
 * is named in the trace, so the panel can show *why* rather than only what.
 */
function evaluate(request, declared, effective) {
    const key = keyOf(request.requested);
    // 1. Fail closed. Never seen this field ⇒ deny.
    if (effective === 'UNCLASSIFIED') {
        return {
            decision: 'DENY',
            rule: 'RULE_UNCLASSIFIED_DENY',
            rationale: `${key} is not in the catalog. Unclassified fields are denied by default.`,
        };
    }
    // 2. Never disclosable by phone or chat, at any verification level.
    if (NEVER_DISCLOSABLE.has(effective)) {
        const inherited = effective !== declared;
        return {
            decision: 'DENY',
            rule: 'RULE_NEVER_BY_PHONE',
            rationale: inherited
                ? `${key} is classified ${declared}, but inherits ${effective} through lineage. Never disclosable by phone.`
                : `${key} is ${effective}. Never disclosable by phone under any verification.`,
        };
    }
    // 3. PII requires a verified data subject, and the subject must be the caller.
    if (effective === 'PII') {
        if (!request.subjectVerified) {
            return {
                decision: 'DENY',
                rule: 'RULE_SUBJECT_UNVERIFIED',
                rationale: `${request.requested.field} is PII and the caller is not yet verified.`,
            };
        }
        if (request.callerSubjectId === undefined ||
            request.rowSubjectId === undefined ||
            request.callerSubjectId !== request.rowSubjectId) {
            return {
                decision: 'DENY',
                rule: 'RULE_SUBJECT_MISMATCH',
                rationale: `Verified caller is not the data subject for this record.`,
            };
        }
        return {
            decision: 'ALLOW',
            rule: 'RULE_SUBJECT_SELF_ALLOW',
            rationale: `Verified data subject reading their own PII.`,
        };
    }
    // 4. Operational data requires verification, but not subject identity.
    if (effective === 'OPERATIONAL') {
        if (!request.subjectVerified) {
            return {
                decision: 'DENY',
                rule: 'RULE_SUBJECT_UNVERIFIED',
                rationale: `${request.requested.field} requires caller verification.`,
            };
        }
        return {
            decision: 'ALLOW',
            rule: 'RULE_OPERATIONAL_ALLOW',
            rationale: `Operational field released to a verified caller.`,
        };
    }
    // 5. Public.
    return {
        decision: 'ALLOW',
        rule: 'RULE_PUBLIC_ALLOW',
        rationale: `Public information.`,
    };
}
/** Monotonic microsecond clock, present in Node and in every browser. */
const nowMicros = () => globalThis.performance.now() * 1000;
/**
 * THE GATE. Resolve, propagate, evaluate, and build the trace. Allow and deny
 * share one shape, because a denial is a decision and not an error.
 */
function adjudicate(graph, request, meta) {
    const t0 = nowMicros();
    const declared = graph.classifySync(request.requested);
    const effective = effectiveOf(graph, request.requested, declared);
    const lineage = declared === 'UNCLASSIFIED' ? [] : graph.lineageSync(request.requested);
    const { decision, rule, rationale } = evaluate(request, declared, effective);
    return {
        traceId: meta.traceId,
        callId: request.callId,
        utterance: request.utterance,
        intent: request.intent,
        requested: request.requested,
        resolvedClassification: declared,
        effectiveClassification: effective,
        decision,
        rule,
        rationale,
        lineage,
        channel: request.channel,
        subjectVerified: request.subjectVerified,
        decidedAt: meta.decidedAt,
        durationMicros: Math.max(1, Math.round(nowMicros() - t0)),
    };
}
/** Splits `table.field`. Field names never contain a dot. */
function refOf(key) {
    const i = key.indexOf('.');
    return { table: key.slice(0, i), field: key.slice(i + 1) };
}
/**
 * CatalogGraph over a snapshot. Breadth-first upstream walk, nearest-first,
 * deduplicated by edge — the same traversal order the SQL recursive CTE
 * produces, which the parity test verifies field by field.
 */
class SnapshotGraph {
    snap;
    constructor(snap) {
        this.snap = snap;
    }
    classifySync(ref) {
        return this.snap.fields[keyOf(ref)]?.classification ?? 'UNCLASSIFIED';
    }
    lineageSync(ref) {
        const out = [];
        const seen = new Set();
        let frontier = [keyOf(ref)];
        // Breadth-first, and within each depth sorted by source key. This is the
        // canonical hop order — it must match the SQL adapter's
        // `ORDER BY depth, from_dataset, from_field` exactly, or the panel would
        // render a different chain than the audit log recorded. core-parity.test.ts
        // asserts the orders agree field by field.
        while (frontier.length > 0) {
            const atDepth = [];
            const next = [];
            for (const node of frontier) {
                for (const e of this.snap.edges) {
                    if (e.to !== node)
                        continue;
                    const id = `${e.from}>${e.to}`;
                    if (seen.has(id))
                        continue;
                    seen.add(id);
                    atDepth.push({
                        from: refOf(e.from),
                        to: refOf(e.to),
                        transform: e.transform,
                        inheritedClassification: this.classifySync(refOf(e.from)),
                    });
                    next.push(e.from);
                }
            }
            // Plain codepoint comparison, NOT localeCompare: the latter is
            // locale-dependent, so Node and a browser under a different default
            // locale could order hops differently and silently break the parity this
            // ordering exists to guarantee. It also loads an ICU collator on first
            // call, which dominated the first decision's latency.
            atDepth.sort((a, b) => (keyOf(a.from) < keyOf(b.from) ? -1 : keyOf(a.from) > keyOf(b.from) ? 1 : 0));
            out.push(...atDepth);
            frontier = next.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
        }
        return out;
    }
}
//# sourceMappingURL=core.js.map
// PORT: ReasonerPort — LOCAL ADAPTER (deterministic, on-device)
// LOCAL ADAPTER: intent match over normalized text + templated responses. Pure
//   functions. No model inference, no network, no wall-clock reads. This adapter
//   IS the Arm Create entry: on-device, arm64, zero-network, $0 per call.
// QUALIFYING ADAPTER: AWS Bedrock — REQUIRED before submitting to
//   CockroachDB × AWS (>=1 AWS service is mandatory there).
// Submitting with only the local adapter = DISQUALIFICATION on that event.
/**
 * Intent → fields that intent needs. Static and exhaustive: the reasoner cannot
 * construct a FieldRef at runtime, so the complete set of reachable field reads
 * is auditable by reading this table. That property is what makes "the refusal
 * is architectural" a checkable claim rather than a slogan.
 */
const INTENT_FIELDS = {
    CLINIC_HOURS: [{ table: 'clinic_info', field: 'hours' }],
    CLINIC_ADDRESS: [{ table: 'clinic_info', field: 'address' }],
    APPOINTMENT_WHEN: [
        { table: 'appointment', field: 'starts_at' },
        { table: 'appointment', field: 'provider_name' },
    ],
    APPOINTMENT_REASON: [{ table: 'appointment', field: 'visit_reason' }],
    REFILL_STATUS: [{ table: 'prescription', field: 'refill_status' }],
    REFILL_DRUG_NAME: [{ table: 'prescription', field: 'drug_name' }],
    BALANCE_DUE: [{ table: 'billing_account', field: 'balance_cents' }],
    RECORDS_REQUEST: [],
    IDENTITY_CONFIRM: [],
    ASK_SSN: [{ table: 'patient', field: 'ssn' }],
    // Routed to the field the caller actually named. It is declared OPERATIONAL,
    // so ONLY lineage propagation from patient.ssn denies it. If this were mapped
    // to patient.ssn instead, a keyword match would be doing the catalog's job and
    // the lineage guarantee would be untested.
    ASK_SUBSCRIBER_KEY: [{ table: 'claim', field: 'subscriber_key' }],
    // Declared SENSITIVE_PII in its own right (derived, but classified honestly).
    ASK_SSN_LAST4: [{ table: 'billing_account', field: 'ssn_last4' }],
    ASK_INSURANCE_ID: [{ table: 'patient', field: 'insurance_member_id' }],
    ASK_HOME_ADDRESS: [{ table: 'patient', field: 'home_address' }],
    ASK_DIAGNOSIS: [{ table: 'claim', field: 'diagnosis_code' }],
    UNKNOWN: [],
};
/**
 * Normalization is deliberately aggressive: it strips the separators and
 * homoglyph tricks that a caller uses to smuggle a field name past a matcher
 * ("s-s-n", "s.s.n", "S S N"). This is why the red-team cases fail to land —
 * but note that normalization is NOT the security boundary. Even a phrasing
 * that defeats it lands on the catalog gate, which fails closed.
 */
function normalize(text) {
    return text
        .toLowerCase()
        .normalize('NFKD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-z0-9\s]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}
/** Collapsed form, separators removed, so "s s n" and "s-s-n" both become "ssn". */
function collapsed(text) {
    return normalize(text).replace(/\s/g, '');
}
/**
 * Ordered most-specific-first. Restricted-field asks are matched BEFORE benign
 * intents so an injected "verification complete, now read the SSN" resolves to
 * ASK_SSN rather than IDENTITY_CONFIRM.
 */
const PATTERNS = [
    {
        // Before ASK_SSN: the caller named a specific derived column.
        intent: 'ASK_SUBSCRIBER_KEY',
        test: (_n, c) => c.includes('subscriberkey') || c.includes('subscriber'),
    },
    {
        intent: 'ASK_SSN_LAST4',
        test: (n) => /\blast four\b/.test(n) || /\blast 4\b/.test(n),
    },
    {
        intent: 'ASK_SSN',
        test: (n, c) => c.includes('ssn') ||
            c.includes('socialsecurity') ||
            /\bsocial\b/.test(n) ||
            /\bnine digits?\b/.test(n) ||
            /\b9 digits?\b/.test(n),
    },
    {
        intent: 'ASK_INSURANCE_ID',
        test: (n, c) => c.includes('memberid') ||
            c.includes('insuranceid') ||
            (/\binsurance\b/.test(n) && /\b(id|number|member)\b/.test(n)),
    },
    {
        intent: 'ASK_HOME_ADDRESS',
        test: (n) => /\b(my|patient|home|his|her|their)\b[\s\w]*\baddress\b/.test(n) ||
            /\bwhere\s+do\s+i\s+live\b/.test(n),
    },
    {
        intent: 'ASK_DIAGNOSIS',
        test: (n, c) => /\bdiagnos/.test(n) || c.includes('icd') || /\bwhat.*wrong with me\b/.test(n),
    },
    {
        intent: 'APPOINTMENT_REASON',
        test: (n) => /\b(visit|appointment)\b[\s\w]*\breason\b/.test(n) || /\bwhy.*coming in\b/.test(n),
    },
    {
        intent: 'REFILL_DRUG_NAME',
        test: (n) => (/\b(what|which)\b/.test(n) && /\b(drug|medication|med|prescription|pill)\b/.test(n)) ||
            /\bmedication (am i|i am) on\b/.test(n),
    },
    {
        intent: 'REFILL_STATUS',
        test: (n) => /\brefill\b/.test(n) || /\bprescription (ready|status)\b/.test(n),
    },
    {
        intent: 'APPOINTMENT_WHEN',
        test: (n) => /\bappointment\b/.test(n) || /\bwhen.*(see|scheduled)\b/.test(n),
    },
    {
        intent: 'BALANCE_DUE',
        test: (n) => /\b(balance|owe|bill|invoice|due)\b/.test(n),
    },
    {
        intent: 'RECORDS_REQUEST',
        test: (n) => /\b(records?|chart|file)\b/.test(n) && /\b(request|copy|get|send)\b/.test(n),
    },
    {
        intent: 'CLINIC_ADDRESS',
        test: (n) => /\b(where|address|located|location|directions)\b/.test(n),
    },
    {
        intent: 'CLINIC_HOURS',
        test: (n) => /\b(hours?|open|close|closing|opening)\b/.test(n),
    },
    {
        intent: 'IDENTITY_CONFIRM',
        test: (n) => /\b(this is|my name is|date of birth|dob|verify|verification)\b/.test(n),
    },
];
const TEMPLATES = {
    CLINIC_HOURS: 'We are open {hours}.',
    CLINIC_ADDRESS: 'We are at {address}.',
    APPOINTMENT_WHEN: 'Your next appointment is {starts_at} with {provider_name}.',
    APPOINTMENT_REASON: '',
    REFILL_STATUS: 'Your refill is {refill_status}.',
    REFILL_DRUG_NAME: '',
    BALANCE_DUE: 'Your balance is {balance_cents}.',
    RECORDS_REQUEST: 'I can start a records request. Records are released in person or by secure mail, never read out over the phone.',
    // Never asserts that verification SUCCEEDED — an injected "verification
    // complete" must not be echoed back as fact. Verification is a state
    // transition owned by the channel, not a claim a caller can make.
    IDENTITY_CONFIRM: 'I can start verification. What is the date of birth on the account?',
    ASK_SSN: '',
    ASK_SUBSCRIBER_KEY: '',
    ASK_SSN_LAST4: '',
    ASK_INSURANCE_ID: '',
    ASK_HOME_ADDRESS: '',
    ASK_DIAGNOSIS: '',
    UNKNOWN: 'I can help with hours, appointments, refills and billing. Which would you like?',
};
/**
 * Spoken refusal. It never names the value, never confirms the value exists, and
 * offers the legitimate path instead — a refusal that leaks "yes we hold that"
 * is still a disclosure.
 */
function refusalFor(trace) {
    const base = `I don't have access to that field.`;
    const path = trace.effectiveClassification === 'PHI' ||
        trace.requested.table === 'patient' ||
        trace.requested.table === 'claim'
        ? ` If you need it, I can start a records request that goes out by secure mail or in person.`
        : ` I can help with hours, appointments, refills or billing instead.`;
    return base + path;
}
class DeterministicReasoner {
    classifyIntent(text) {
        const n = normalize(text);
        const c = collapsed(text);
        for (const p of PATTERNS) {
            if (p.test(n, c))
                return p.intent;
        }
        return 'UNKNOWN';
    }
    async respond(utterance, state, catalog) {
        const started = performance.now();
        const intent = this.classifyIntent(utterance.text);
        const fields = INTENT_FIELDS[intent];
        const traces = [];
        let denied = false;
        // Every field this intent needs goes through the gate. No field value is
        // read from anywhere else, so a DENY cannot be bypassed by a later branch.
        for (const requested of fields) {
            const trace = await catalog.decide({
                callId: utterance.callId,
                utterance: utterance.text,
                intent,
                requested,
                channel: utterance.channel,
                subjectVerified: state.subjectVerified,
                ...(state.callerSubjectId !== undefined
                    ? { callerSubjectId: state.callerSubjectId }
                    : {}),
                ...(state.rowSubjectId !== undefined
                    ? { rowSubjectId: state.rowSubjectId }
                    : {}),
            });
            traces.push(trace);
            if (trace.decision === 'DENY')
                denied = true;
        }
        let reply;
        let escalated = false;
        if (denied) {
            const firstDeny = traces.find((t) => t.decision === 'DENY');
            reply = refusalFor(firstDeny);
        }
        else if (intent === 'UNKNOWN') {
            reply = TEMPLATES.UNKNOWN;
            escalated = false;
        }
        else {
            // Templates are filled ONLY from ALLOWED traces, via readValue(trace).
            // A placeholder with no allowed source is never substituted, so a partial
            // value cannot slip into a reply.
            let filled = TEMPLATES[intent] || TEMPLATES.UNKNOWN;
            const reader = catalog;
            if (typeof reader.readValue === 'function') {
                for (const t of traces) {
                    if (t.decision !== 'ALLOW')
                        continue;
                    const v = reader.readValue(t, state.rowSubjectId ?? '*');
                    if (v !== undefined) {
                        filled = filled.replaceAll(`{${t.requested.field}}`, v);
                    }
                }
            }
            // Any unsubstituted placeholder means no allowed source existed.
            reply = /\{[a-z_]+\}/.test(filled) ? TEMPLATES.UNKNOWN : filled;
            if (intent === 'RECORDS_REQUEST')
                escalated = true;
        }
        return {
            reply,
            intent,
            traces,
            resolvedUnassisted: !escalated,
            escalatedToHuman: escalated,
            latencyMicros: Math.round((performance.now() - started) * 1000),
        };
    }
}
//# sourceMappingURL=deterministic.js.map

export const SNAPSHOT = {
  "fields": {
    "appointment.appt_id": {
      "classification": "OPERATIONAL",
      "justification": "Scheduling key"
    },
    "appointment.provider_name": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "appointment.starts_at": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "appointment.visit_reason": {
      "classification": "PHI",
      "justification": "Clinical reason for the visit"
    },
    "billing_account.account_id": {
      "classification": "OPERATIONAL",
      "justification": "Billing key"
    },
    "billing_account.balance_cents": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "billing_account.ssn_last4": {
      "classification": "SENSITIVE_PII",
      "justification": "Derived from patient.ssn; still identifying"
    },
    "claim.claim_id": {
      "classification": "OPERATIONAL",
      "justification": "Claim key"
    },
    "claim.diagnosis_code": {
      "classification": "PHI",
      "justification": "ICD-10 code is diagnosis in the clear"
    },
    "claim.subscriber_key": {
      "classification": "OPERATIONAL",
      "justification": "Operator believed this was an opaque key"
    },
    "claim_export.row_id": {
      "classification": "OPERATIONAL",
      "justification": "Export row key"
    },
    "claim_export.subscriber_key": {
      "classification": "OPERATIONAL",
      "justification": "Copied verbatim into the clearinghouse file"
    },
    "clinic_info.address": {
      "classification": "PUBLIC",
      "justification": "Public listing"
    },
    "clinic_info.hours": {
      "classification": "PUBLIC",
      "justification": "Posted on the front door and the website"
    },
    "clinic_info.phone": {
      "classification": "PUBLIC",
      "justification": "Public listing"
    },
    "patient.date_of_birth": {
      "classification": "PII",
      "justification": "Identifier used for verification; never read back to a caller"
    },
    "patient.first_name": {
      "classification": "PII",
      "justification": "Identifies the data subject"
    },
    "patient.home_address": {
      "classification": "SENSITIVE_PII",
      "justification": "Physical safety risk for patients with protective orders"
    },
    "patient.insurance_member_id": {
      "classification": "SENSITIVE_PII",
      "justification": "Enables benefits fraud if disclosed"
    },
    "patient.last_name": {
      "classification": "PII",
      "justification": "Identifies the data subject"
    },
    "patient.patient_id": {
      "classification": "OPERATIONAL",
      "justification": "Internal surrogate key, not disclosable but not identifying alone"
    },
    "patient.phone": {
      "classification": "PII",
      "justification": "Contact identifier"
    },
    "patient.ssn": {
      "classification": "SENSITIVE_PII",
      "justification": "Full SSN. Never disclosable by phone under any verification"
    },
    "prescription.drug_name": {
      "classification": "PHI",
      "justification": "Reveals diagnosis by inference"
    },
    "prescription.prescriber_note": {
      "classification": "PHI",
      "justification": "Clinical note"
    },
    "prescription.refill_status": {
      "classification": "OPERATIONAL",
      "justification": "Disclosable to the verified data subject"
    },
    "prescription.rx_id": {
      "classification": "OPERATIONAL",
      "justification": "Refill key"
    }
  },
  "edges": [
    {
      "from": "appointment.visit_reason",
      "to": "claim.diagnosis_code",
      "transform": "derive"
    },
    {
      "from": "billing_account.ssn_last4",
      "to": "claim.subscriber_key",
      "transform": "derive"
    },
    {
      "from": "claim.subscriber_key",
      "to": "claim_export.subscriber_key",
      "transform": "copy"
    },
    {
      "from": "patient.date_of_birth",
      "to": "claim.subscriber_key",
      "transform": "derive"
    },
    {
      "from": "patient.patient_id",
      "to": "appointment.appt_id",
      "transform": "join"
    },
    {
      "from": "patient.patient_id",
      "to": "billing_account.account_id",
      "transform": "join"
    },
    {
      "from": "patient.ssn",
      "to": "billing_account.ssn_last4",
      "transform": "derive"
    },
    {
      "from": "prescription.drug_name",
      "to": "claim.diagnosis_code",
      "transform": "derive"
    }
  ],
  "values": {
    "appointment.provider_name": {
      "p_1001": "Dr. Amara Osei"
    },
    "appointment.starts_at": {
      "p_1001": "Thursday August 6th at 2:15pm"
    },
    "appointment.visit_reason": {
      "p_1001": "follow-up, elevated A1C"
    },
    "billing_account.balance_cents": {
      "p_1001": "4250"
    },
    "billing_account.ssn_last4": {
      "p_1001": "4021"
    },
    "claim.diagnosis_code": {
      "p_1001": "E11.9"
    },
    "claim.subscriber_key": {
      "p_1001": "4021-19540311"
    },
    "claim_export.subscriber_key": {
      "p_1001": "4021-19540311"
    },
    "clinic_info.address": {
      "*": "4120 Larkspur Avenue, Suite 3"
    },
    "clinic_info.hours": {
      "*": "Monday to Friday, 8am to 6pm"
    },
    "clinic_info.phone": {
      "*": "(555) 0142-8890"
    },
    "patient.date_of_birth": {
      "p_1001": "1954-03-11"
    },
    "patient.first_name": {
      "p_1001": "Dolores"
    },
    "patient.home_address": {
      "p_1001": "18 Rosewood Lane, Apt 2B"
    },
    "patient.insurance_member_id": {
      "p_1001": "BCBS-99120445"
    },
    "patient.last_name": {
      "p_1001": "Whitfield"
    },
    "patient.phone": {
      "p_1001": "(555) 0177-2311"
    },
    "patient.ssn": {
      "p_1001": "539-88-4021"
    },
    "prescription.drug_name": {
      "p_1001": "metformin 500mg"
    },
    "prescription.prescriber_note": {
      "p_1001": "poorly controlled, increase dose"
    },
    "prescription.refill_status": {
      "p_1001": "ready for pickup"
    }
  }
};

// The exports the page consumes. Everything above is unmodified compiled code.
export { adjudicate, effectiveOf, evaluate, SnapshotGraph, keyOf, refOf,
         RESTRICTION_ORDER, NEVER_DISCLOSABLE, rank };
export { DeterministicReasoner, INTENT_FIELDS, normalize };
